### ISSUE TITLE
Bump scikit-learn dep version to include 0.24.0

### ISSUE THREAD

**Issue by MrBlenny** [borchero/pyblaze#5]
Hi,
I'm super impressed with this work and very keen to use `pycave` for some real-time GMM fitting.

I note that the `pyblaze` requirements.txt lists `scikit-learn>=0.23.0,<0.24.0`. I'm running this project on an ARM64 Nvidia Xavier and scikit does not have arm wheels until v0.24 (compiling scikit-learn on such a small device is untenable). Is this strict dependency pin necessary? I have been unable to run the tests but it would be great if we could get this working with the latest version of scikit-learn.

Thanks!

**Comment by borchero** [comment]
Very sorry for the late reply! Fixed in 2.3.1
